# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-15 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('isdelete', models.BooleanField(default=False)),
            ],
        ),
    ]
